apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: extproc-backend-tls
  namespace: kgateway-system
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: extprocserver

  validation:
    caCertificateRefs:
      - group: ""
        kind: Secret
        name: extproc-ca

    hostname: extprocserver   # must match cert SAN/CN
